version: "3.7"
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8090:8080
    environment:
      - PORT=8080
      - DBURL=mysql
      - DBUSER=root
      - DBPASSWORD=password
      - DBDATABASE=todo
      - DBPORT=3306
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      args:
        - APIURL=http://localhost:8090
    ports:
      - 80:80
      
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./backend/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password