version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DBURL=mongodb://mongo:27017/todo
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
      
  mongo:
    image: mongo
    ports:
      - 27017:27017